### ISSUE TITLE
P1 Caged Turret is somehow defective

### ISSUE THREAD

**Issue by alias-old** [ENDERZOMBI102/Retro-Station#22]
![preview0003](https://user-images.githubusercontent.com/58821795/97043735-96cb5200-157b-11eb-90c2-e00c1e8a8f1c.jpg)

**Comment by ENDERZOMBI102** [comment]
what style is it?

**Comment by alias-old** [comment]
Portal 1

**Comment by ENDERZOMBI102** [comment]
strange i've used it in a P1 map
may you send logs of the compilation and the map? (compiled and not)

**Comment by alias-old** [comment]
I am not much of a source engine expert so lemme try

**Comment by alias-old** [comment]
The log on the dev console you mean?

**Comment by ENDERZOMBI102** [comment]
no, the one in P2dir/bin/bee2/

**Comment by alias-old** [comment]
![vrad](https://user-images.githubusercontent.com/58821795/97751141-8165a300-1afa-11eb-9e15-aa38e5a9f6b6.PNG)
It appears you used wrong turret model (seen in vrad.txt after map compile)
[vrad.log](https://github.com/ENDERZOMBI102/Retro-Station/files/5467346/vrad.log)
You used "models/bee2/props_underground/turret_skeleton.mdl"
While it should be "models/bee2/props_p1/turret_01.mdl"

**Comment by ENDERZOMBI102** [comment]
fixed 👌
