### ISSUE TITLE
Make Laser Cube always face ahead

### ISSUE THREAD

**Issue by MeatyShitter** [ENDERZOMBI102/Retro-Station#3]
The default package [Cube Bomb] has a custom reflective cube that faces forwards when held.

**Comment by Flash4433** [comment]
That actually is true. The Cube Bomb uses the Reflective Cube model. It's just painted red, and I think some other models inside of it. You can paint a model directly in Hammer.

I would love to make it always face ahead, but I don't think it's possible. 

I'm gonna leave this open, in hopes I can later on add that functionality. But yes, it only works on that specific model, and it's not a variable we can simply add to another model.

Also, we're making huge changes to these packages, as it seems they weren't properly working.

**Comment by Flash4433** [comment]
I was able to make it always face ahead by removing the useless collision from a model that was inside the cube.
