### ISSUE TITLE
Paint Detector

### ISSUE THREAD

**Issue by Sand-Scientist** [ENDERZOMBI102/Retro-Station#5]
This item would function like a laser catcher/bridge catcher etc.  When it gets painted by a certain paint, it releases an output.  Maybe with a start enabled for pre-painted and start reversed for it to require constant painting instead of just one blob.

Until now, I have just been using paint activator cubes, but this would be very useful =)

**Comment by Sand-Scientist** [comment]
Btw, I am posting ideas here instead of in the official place for Bee, because things here tend to be more likely to be made, made faster and to a higher quality =D

**Comment by ENDERZOMBI102** [comment]
A paint detector is impossible

**Comment by ENDERZOMBI102** [comment]
Even valve, that has (obiusly) source code access, in the sections where the paint “should” be detected, they used a portal detector

**Comment by ENDERZOMBI102** [comment]
And thanks for the compliment! 😄

**Comment by Flash4433** [comment]
> Btw, I am posting ideas here instead of in the official place for Bee, because things here tend to be more likely to be made, made faster and to a higher quality =D

Ah, thank you. I'm not sure about the third, but I think we can manage the first 2 :)

Unfortunately, I was already thinking about how to make this item, however, Portal 2 can't detect blobs or gel-splatted surfaces. The cubes have a `OnPainted` output, and that's it to detect gel. I suggest you use carefully placed Portal Detectors, Portal Magnets and white surfaces for that. Portal Stories Mel did an excellent job with that:

 There's a fire and a "water" (gel) dropper nearby. You can only put a portal next to them in specific places: these two places have portal detectors. If the two portal detectors are active, then that means the "water" is touching the flames, so the portal detectors output and the fire extinguishes.

I suggest you use tricks like these so it seems it's detecting the gel. Sorry :P

**Comment by Sand-Scientist** [comment]
Thx for the advice, this lead to another idea though =).
