### ISSUE TITLE
TNT Turret broke something (Downloaded via Master ZIP File)

### ISSUE THREAD

**Issue by CubieJudy** [ENDERZOMBI102/Retro-Station#8]
> Traceback (most recent call last):
>   File "F:\Git\BEE2.4\src\BEE2_launch.pyw", line 50, in <module>
>   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
>   File "F:\Git\BEE2.4\src\BEE2.py", line 92, in <module>
>   File "F:\Git\BEE2.4\src\packageLoader.py", line 441, in load_packages
>   File "F:\Git\BEE2.4\src\packageLoader.py", line 357, in find_packages
>   File "F:\Git\srctools\srctools\filesys.py", line 115, in read_prop
>   File "F:\Git\srctools\srctools\property_parser.py", line 251, in parse
> srctools.property_parser.KeyValError: Property cannot have sub-section if it already has an in-line value.
> 
> A "name" "value" line cannot then open a block.
> Error occurred on line 21, with file "C:\Users\keith\Desktop\Beemod\packages\Retro-Station-master:info.txt".
>

**Comment by Flash4433** [comment]
Thank you, I forgot to remove that extra line. I already fixed it.

**Comment by CubieJudy** [comment]
Ah! I was just about to say i figured out what happened! Awesome to hear this! Can't wait!

**Comment by Flash4433** [comment]
It was an issue with the 50's TNT Turret, I forgot to remove a line from the example I used. Basically, it was searching for the files in an empty folder. Not only that but it had to override stuff that didn't exist. Removing that extra line made it use Clean's TNT Turret as a base so it could do the necessary overrides. Thank you for bringing this to our attention!

**Comment by CubieJudy** [comment]
Ah ha! However I do believe there is more issues.

With the lines seen here
{
						"0" "icon" "palette/oldAp/redturret.png"
						"0" "bee2" "oldAp/redturret.png"
					}

It gives an error for having two names in both. I delete the "icon" and "bee2" respectively and it works. However then it gives me

> > Traceback (most recent call last):
>   File "F:\Git\BEE2.4\src\BEE2_launch.pyw", line 50, in <module>
>   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
>   File "F:\Git\BEE2.4\src\BEE2.py", line 92, in <module>
>   File "F:\Git\BEE2.4\src\packageLoader.py", line 548, in load_packages
>   File "F:\Git\BEE2.4\src\packageLoader.py", line 728, in setup_style_tree
>   File "F:\Git\BEE2.4\src\packageLoader.py", line 1057, in modify
>   File "F:\Git\BEE2.4\src\packageLoader.py", line 1080, in _modify_editoritems
>   File "F:\Git\srctools\srctools\property_parser.py", line 707, in __getitem__
> ValueError: Can't index a Property without children!

Unsure what this means, but it goes away when i remove the retro pack

**Comment by Flash4433** [comment]
Ugh, that's weird... Oh well, I'll have to test it out some more.For that Property error, let me quickly check if the problem is what I think it is...

**Comment by Flash4433** [comment]
Did you also remove the `"Palette"` part? You should remove everything in this screenshot that's on the info.txt. I'll make the needed changes tomorrow, as it's midnight in my zone :P

**Comment by Flash4433** [comment]
![Screenshot_20200222-235444-725](https://user-images.githubusercontent.com/38331230/75101088-207ee600-55cf-11ea-9f63-982e4c5e2698.png)

**Comment by Flash4433** [comment]
For some reason, it didn't upload my change two days ago... Fixed now.
